### ISSUE TITLE
smartfritz

### ISSUE THREAD

**Issue by ageorgios** [tommasomarchionni/homebridge-FRITZBox#6]
You can use
https://github.com/nischelwitzer/smartfritz

instead of your api to speed up the develpoment process

I would really like to see progress for the smart switch (Fritz!DECT200) where we could turn on/off via homebridge.

Great work thank you!

**Comment by wiesmann** [comment]
An alternative would be to use the TR-064 API which is the official way of configuring the device.

https://github.com/hendrikw01/tr-064

**Comment by andig** [comment]
I would actually suggest this api: https://github.com/andig/smartfritz 

It has more functions and is promise-based opposed to the original smartfritz implementation. Wifi guest access does not yet work reliably though.

If no interest here I'll check for forking this repo and adding CometDECT support.

**Comment by andig** [comment]
I've reimplemented the whole thing and added support for Fritz Outlets and Thermostats, see https://github.com/andig/homebridge-fritz
